### ISSUE TITLE
mw-headline padding-top obscures h3 links on small screens / mobile

### ISSUE THREAD

**Issue by badshah400** [borkweb/bootstrap-mediawiki#80]
Thanks for this really awesome theme!

The mw-headline padding-top of 103px  obscures h3 links making them unclickable. Changing the padding-top to 10px and margin-top to -10px seems to fix this (see line#478 in style.css):

```css
@media (max-width: 979px) {
	body { padding-top: 103px; }

	.mw-headline {
		margin-top: -103px;
		padding-top: 103px;
	}
```

For a demo, try to click on the link "1. Gauge invariance, relation with GR, large transformations, Wilson loop." on this page:
http://www.theo.phys.ulg.ac.be/wiki/Astro-particules
from a mobile or by resizing your browser so that the md size theme kicks in. The links can't be clicked. 

These modifications were introduced as part of commit a5ddee385e6b461fd809e915200a64c78b110ebe, but simply keeping `body { padding-top: 103px; }` should be enough to prevent the title from slipping under the navbar (seems to work in my case, where I have changed the mw-headline padding-top to 10px from 103px but left the body padding-top unaltered).

Thanks for any help or suggestions.
